### PR TITLE
Vulkan: Fix mipped render target barrier inconsistencies

### PR DESCRIPTION
**Pull request by thatcosmonaut**
Real fix for #183

### CODE REVIEW

**Comment by kg** [comment]
This doesn't seem to fix it, maybe I did something wrong when testing it locally. Maybe something else is also trying to transition all the mips?
image

**Comment by kg** [comment]
We discussed on discord that there are other problems at work explaining why I get validation errors. This change still seems correct

**Comment by thatcosmonaut** [comment]
Fixes #188

**Review by flibitijibibo — APPROVED** [review]
Nothing stands out to me, so if this is the final draft it can be squashed in.

**Pull request merged**
